### ISSUE TITLE
Just a question on code

### ISSUE THREAD

**Issue by builderjer** [LinusS1/communications-skill#16]
I am reading through your code, and noticed in your shippingandhandling.py file, there is a section of code I do not understand.

`>>>>>>> HEAD

lots of code

=======`

I have never seen this before and was wondering if you could explain it's use for me.

Thank you

**Comment by LinusSkucas** [comment]
Hey there, I'm not sure where you're seeing that. It's not on GitHub, so you must have pulled it yourself?

To answer you question, it's what happens when there's a merge conflict with git. Git edits the file so you can see which version you want to keep.

**Comment by builderjer** [comment]
Makes sense.  That is what I did.  I will close the issue.  Thank you
